#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: hack/update_versions.sh [OPTIONS]

Regenerate a data/versions/<version>.yaml pin file from upstream
cozystack/cozystack, so the {{< version-pin >}} values never go stale.

Sources of truth:
  * talos / talos_minor     ← packages/core/talos/images/talos/profiles/installer.yaml
                              at --branch (always the version main/the tag ships).
  * cozystack_version/_tag  ← --cozystack-tag if given (e.g. an upcoming release
                              tag); otherwise the latest final upstream release
                              tag. Used as the `next` trunk's resolvable default
                              until the real release is cut.

Options:
  --dest PATH           data/versions/<version>.yaml file to (re)generate (required)
  --branch REF          Git ref in cozystack/cozystack to read the Talos installer
                        from (default: main)
  --cozystack-tag TAG   Pin cozystack_tag to this vX.Y.Z tag instead of the latest
                        release (optional)
  -h, --help            Show this help and exit

Examples:
  hack/update_versions.sh --dest data/versions/next.yaml --branch main
  hack/update_versions.sh --dest data/versions/next.yaml --branch v1.6.0 --cozystack-tag v1.6.0
EOF
}

SOURCE_REPO="cozystack/cozystack"
DEST=""
BRANCH="main"
COZYSTACK_TAG=""

# -------------------- Parse arguments --------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest|--branch|--cozystack-tag)
      # Guard the value-taking flags: without this, a missing value makes the
      # `$2` read trip `set -u` ("unbound variable") instead of a clean usage error.
      if [[ $# -lt 2 ]]; then
        echo "Error: $1 requires a value." >&2
        usage; exit 1
      fi
      case "$1" in
        --dest)          DEST="$2" ;;
        --branch)        BRANCH="$2" ;;
        --cozystack-tag) COZYSTACK_TAG="$2" ;;
      esac
      shift 2 ;;
    -h|--help)       usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "$DEST" ]]; then
  echo "Error: --dest is required." >&2
  usage; exit 1
fi

# -------------------- 1. Talos version from the installer profile --------------------
INSTALLER_PATH="packages/core/talos/images/talos/profiles/installer.yaml"
INSTALLER_URL="https://raw.githubusercontent.com/${SOURCE_REPO}/${BRANCH}/${INSTALLER_PATH}"
talos="$(curl -fsSL "$INSTALLER_URL" 2>/dev/null | awk '/^version:[[:space:]]/{print $2; exit}' || true)"
if [[ ! "$talos" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Error: could not read a Talos version from $INSTALLER_URL (got '${talos:-}')." >&2
  exit 1
fi
talos_minor="${talos%.*}"   # v1.13.0 -> v1.13

# -------------------- 2. Cozystack release tag --------------------
if [[ -z "$COZYSTACK_TAG" ]]; then
  # Latest final release: top-level refs/tags/vX.Y.Z only (excludes the
  # api/apps/v1alpha1/* submodule tags and any -rc/-beta pre-releases).
  COZYSTACK_TAG="$(git ls-remote --tags --refs "https://github.com/${SOURCE_REPO}.git" 'v*.*.*' \
    | awk -F/ '/refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$/{print $NF}' \
    | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)"
fi
if [[ ! "$COZYSTACK_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Error: could not determine a cozystack release tag (got '${COZYSTACK_TAG:-}')." >&2
  exit 1
fi
cozystack_version="${COZYSTACK_TAG#v}"

# -------------------- 3. (Re)generate the pin file --------------------
mkdir -p "$(dirname "$DEST")"
cat > "$DEST" <<EOF
# AUTOGENERATED by hack/update_versions.sh — do not edit by hand.
#
# Regenerated by 'make update-all' so the {{< version-pin >}} values in the
# next/ trunk track upstream cozystack/cozystack@${BRANCH}:
#
#   talos / talos_minor       ← ${INSTALLER_PATH} @ ${BRANCH}
#   cozystack_version / _tag   ← latest final release tag (the upcoming release's
#                                own tag/assets don't exist until it is cut;
#                                hack/release_next.sh overrides these from
#                                RELEASE_TAG when next/ is promoted).

# Cozystack release the docs are pinned to.
cozystack_version: "${cozystack_version}"   # bare, as used by \`helm --version\`
cozystack_tag:     "${COZYSTACK_TAG}"  # v-prefixed, as used in GitHub URLs

# Talos version shipped by the Cozystack installer for this trunk.
talos:       "${talos}"
talos_minor: "${talos_minor}"           # the docs minor used by talos.dev URLs
EOF

echo "✓ Regenerated $DEST (cozystack_tag=${COZYSTACK_TAG}, talos=${talos}, from ${SOURCE_REPO}@${BRANCH})"
