#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: hack/update_apps.sh [OPTIONS]

Options:
  --branch BRANCH       Git ref in cozystack/cozystack used to FETCH README content (default: main)
  --source-ref REF      Git ref written into the displayed `source:` URL inside generated files.
                        Defaults to --branch if omitted. Use a stable ref (e.g., release-1.2) to
                        avoid flipping the source URL on every patch release.
  --apps  LIST          Space- or comma-separated list of apps to update
  --dest  PATH          Destination directory to write the *.md files to
  --pkgdir DIR          Subdirectory under packages/ to fetch from (default: apps). Examples: apps, extra
  --index               Write each app into path/<app>/_index.md instead of path/<app>.md (creates subdirectory)
  -h, --help            Show this help and exit

Notes:
  * Template markdown files are expected in DEST_DIR/_include (derived automatically).
  * Each template file should be named <app>.md.

Examples:
  hack/update_apps.sh --apps "tenant redis" --dest content/en/docs/reference/applications
  hack/update_apps.sh --apps "tenant,redis" --dest content/en/docs/reference/applications --branch feature/foo
EOF
}

BRANCH="main"
SOURCE_REF=""
DEST_DIR=""
APPS=()
INDEX_MODE="false"
PKG_DIR="apps"

# -------------------- Parse arguments --------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch)
      BRANCH="$2"; shift 2 ;;
    --source-ref)
      SOURCE_REF="$2"; shift 2 ;;
    --apps)
      IFS=', ' read -r -a APPS <<< "$2"; shift 2 ;;
    --dest)
      DEST_DIR="$2"; shift 2 ;;
    --pkgdir)
      PKG_DIR="$2"; shift 2 ;;
    --index)
      INDEX_MODE="true"; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      # allow trailing positional apps as well
      if [[ "$1" == --* ]]; then
        echo "Unknown option: $1" >&2
        usage; exit 1
      else
        APPS+=("$1"); shift
      fi
      ;;
  esac
done

if [[ ${#APPS[@]} -eq 0 ]]; then
  echo "Error: no apps specified. Use --apps." >&2
  usage; exit 1
fi

if [[ -z "$DEST_DIR" ]]; then
  echo "Error: --dest is required." >&2
  usage; exit 1
fi

# Derive templates location: DEST_DIR/_include
SRC_DIR="${DEST_DIR%/}/_include"

# If --source-ref wasn't given, fall back to the fetch branch (preserves prior behavior)
SOURCE_REF="${SOURCE_REF:-$BRANCH}"

DOCS_REPO="cozystack/website"
SOURCE_REPO="cozystack/cozystack"
RAW_BASE_URL="https://raw.githubusercontent.com/${SOURCE_REPO}/${BRANCH}/packages/${PKG_DIR}"


for app in "${APPS[@]}"; do
  if [[ "$INDEX_MODE" == "true" ]]; then
    src_file="${DEST_DIR%/}/${app}/_include/_index.md"
    dest_file="${DEST_DIR%/}/${app}/_index.md"
  else
    if [[ "$app" == "monitoring" ]]; then
      src_file="${DEST_DIR%/}/_include/parameters.md"
      dest_file="${DEST_DIR%/}/monitoring/parameters.md"
    else
      src_file="${DEST_DIR%/}/_include/${app}.md"
      dest_file="${DEST_DIR%/}/${app}.md"
    fi
  fi

  # Ensure template exists (touch if missing)
  [[ -f "$src_file" ]] || touch "$src_file"

  # Copy template to destination (overwrite)
  cp "$src_file" "$dest_file"

  # Insert autogenerated notice with links
  rel_template_path="${src_file#./}"
  cat >> "$dest_file" <<EOF
<!--
Autogenerated content. Don't edit this file directly; edit sources instead.
metadata: https://github.com/${DOCS_REPO}/blob/main/${rel_template_path}
source: https://github.com/${SOURCE_REPO}/blob/${SOURCE_REF}/packages/${PKG_DIR}/${app}/README.md
-->

EOF

  readme_url="${RAW_BASE_URL}/${app}/README.md"
  echo "Processing $app..."

  if curl -fsSL --compressed "$readme_url" \
    | sed '1s/\xEF\xBB\xBF//' \
    | awk 'NR==1 && /^#{1,2} / { next } { print }' >> "$dest_file"; then
    echo "✓ Appended README for $app -> $dest_file"
  else
    echo "⚠️  Failed to fetch README for $app" >&2
  fi

done